spring.application.name=slotBook
spring.datasource.url=jdbc:postgresql://localhost:5432/slotbook?options=-c%20TimeZone=UTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET:my-super-secret-key-for-slotbook-jwt-token-2026}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email